config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :teams do
      post :verified_email
    end
    resources :users do
      post :sync
    end
    resources :custom_email_addresses
    resources :beta_signups
    resources :changelogs
    resources :site_options

    root to: "teams#index"
  end

  namespace :events do
    post "/postmark", to: "postmark_webhooks#create"
  end

  namespace :api, format: :json do
    scope path: ":team_publishable_key" do
      resources :customers, only: :create
      resources :messages, only: :create
    end
  end

  devise_for :users, controllers: {
    registrations: "user_registrations",
    masquerades: "admin/masquerades",
  }

  authenticated :user, ->(u) { u.role?(:admin) } do
    mount Sidekiq::Web => "/sidekiq"
    mount Blazer::Engine, at: "blazer"
    mount Lookbook::Engine, at: "/lookbook"
  end

  # Stripe webhooks
  mount StripeEvent::Engine, at: "/events/stripe"

  resources :beta_signups, only: :create
  namespace :billing do
    resource :subscriptions, path: "subscription", only: %i[show create]
    get :success, to: "subscriptions#success"
    post :manage, to: "subscriptions#manage"
  end
  resources :blocked_domains, only: %i[create destroy]
  resources :canned_responses, only: %i[new create edit update destroy]
  resources :custom_email_addresses, only: %i[create destroy]
  resources :customers do
    get "search", on: :collection
    post "block", on: :member
    post "unblock", on: :member
  end
  resources :knowledge_base, only: [:index, :create, :show, :destroy], path: "knowledge-base"
  resources :message_threads, only: %i[index show new create update destroy], path: "threads" do
    get :search, on: :collection
    get :spam, on: :collection
    get :blocked, on: :collection
    post :merge_with_previous, on: :member
    delete :auto_archive, on: :collection
    resource :generate_reply, only: :create, controller: "ai/generate_reply", as: :ai_generate_reply
    resources :messages, only: %i[new create update destroy] do
      get :hovercard, on: :member
      get :raw_source, on: :member
      get :original_html, on: :member
      get :context, on: :member

      resource :spam_check, only: :create, controller: "messages/spam_checks"
    end
  end
  resources :teams, only: %i[index new create edit update] do
    post :change, on: :member
    put :logo_upload, on: :member
  end
  resources :team_users, only: %i[update destroy]
  resource :settings, only: %i[show] do
    get :team
    get :emails
    get :canned_responses
    get :widget
    get :billing
    get :blocked_domains
    get :spam
    put :spam_update
  end
  namespace :image_uploads do
    resources :logo, controller: "logo", only: :show
  end
  get "/join/:code", to: "team_invites#new", as: :join_team
  post "/join/:code", to: "team_invites#create"
  put "/join/:code", to: "team_invites#update"
  get "/view_message/:id", to: "messages#view_message", as: :view_message

  get "/dashboard", to: "dashboard#show"
  get "/auth/check", to: "auth#check"

  root to: "dashboard#show"
end

app/controllers/admin/custom_email_addresses_controller.rb
module Admin
  class CustomEmailAddressesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    def scoped_resource
      resource_class.unscoped
    end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/custom_email_addresses_controller.rb
class CustomEmailAddressesController < ApplicationController
  def create
    @custom_email_address = current_team.custom_email_addresses.new(custom_email_params)

    if @custom_email_address.save
      TeamMailer.email_awaiting_approval(current_team, @custom_email_address.email).deliver_later

      AdminMailer.notification(
        "Custom email needs confirmed!",
        "#{current_team.name} just added #{@custom_email_address.email} and it needs confirmed."
      ).deliver_later

      redirect_to emails_settings_path, notice: t(".success", email: @custom_email_address.email)
    else
      render partial: "form", status: :unprocessable_entity
    end
  end

  def destroy
    custom_email = current_team.custom_email_addresses.find(params[:id])
    custom_email.destroy
    redirect_to emails_settings_path, notice: t(".removed", email: custom_email.email)
  end

  private

  def custom_email_params
    params.require(:custom_email_address).permit(:email, :from_name)
  end
end

app/views/custom_email_addresses/_custom_email_address.html.erb
<div class="mb-3 flex items-center" data-id="<%= custom_email_address.id %>">
  <% if custom_email_address.confirmed_at? %>
    <svg class="text-green-500 h-5 mr-3 flex-shrink-0" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
    </svg>
  <% else %>
    <svg title="Check your email address to confirm" class="text-gray-400 h-5 mr-3" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
      <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd" />
    </svg>
  <% end %>
  <span class="flex-grow text-sm"><%= custom_email_address.to_s %></span>
  <%= button_to custom_email_address_path(custom_email_address), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "flex items-center flex-shrink-0 text-sm text-gray-500 hover:text-gray-800" do %>
    <%= t(".remove") %>
    <svg class="ml-1 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
      <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
    </svg>
  <% end %>
</div>

app/views/custom_email_addresses/_form.html.erb
<%= form_with(model: @custom_email_address, class: "mt-5 styled-form") do |f| %>
  <div class="flex flex-col">
    <%= f.email_field :email, placeholder: t(".email_placeholder"), class: "mb-2" %>
    <%= f.text_field :from_name, placeholder: t(".from_placeholder"), class: "mb-2" %>
    <%= f.submit t(".button"), class: "button -primary" %>
  </div>
<% end %>