config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :teams do
      post :verified_email
    end
    resources :users do
      post :sync
    end
    resources :custom_email_addresses
    resources :beta_signups
    resources :changelogs
    resources :site_options

    root to: "teams#index"
  end

  namespace :events do
    post "/postmark", to: "postmark_webhooks#create"
  end

  namespace :api, format: :json do
    scope path: ":team_publishable_key" do
      resources :customers, only: :create
      resources :messages, only: :create
    end
  end

  devise_for :users, controllers: {
    registrations: "user_registrations",
    masquerades: "admin/masquerades",
  }

  authenticated :user, ->(u) { u.role?(:admin) } do
    mount Sidekiq::Web => "/sidekiq"
    mount Blazer::Engine, at: "blazer"
    mount Lookbook::Engine, at: "/lookbook"
  end

  # Stripe webhooks
  mount StripeEvent::Engine, at: "/events/stripe"

  resources :beta_signups, only: :create
  namespace :billing do
    resource :subscriptions, path: "subscription", only: %i[show create]
    get :success, to: "subscriptions#success"
    post :manage, to: "subscriptions#manage"
  end
  resources :blocked_domains, only: %i[create destroy]
  resources :canned_responses, only: %i[new create edit update destroy]
  resources :custom_email_addresses, only: %i[create destroy]
  resources :customers do
    get "search", on: :collection
    post "block", on: :member
    post "unblock", on: :member
  end
  resources :knowledge_base, only: [:index, :create, :show, :destroy], path: "knowledge-base"
  resources :message_threads, only: %i[index show new create update destroy], path: "threads" do
    get :search, on: :collection
    get :spam, on: :collection
    get :blocked, on: :collection
    post :merge_with_previous, on: :member
    delete :auto_archive, on: :collection
    resource :generate_reply, only: :create, controller: "ai/generate_reply", as: :ai_generate_reply
    resources :messages, only: %i[new create update destroy] do
      get :hovercard, on: :member
      get :raw_source, on: :member
      get :original_html, on: :member
      get :context, on: :member

      resource :spam_check, only: :create, controller: "messages/spam_checks"
    end
  end
  resources :teams, only: %i[index new create edit update] do
    post :change, on: :member
    put :logo_upload, on: :member
  end
  resources :team_users, only: %i[update destroy]
  resource :settings, only: %i[show] do
    get :team
    get :emails
    get :canned_responses
    get :widget
    get :billing
    get :blocked_domains
    get :spam
    put :spam_update
  end
  namespace :image_uploads do
    resources :logo, controller: "logo", only: :show
  end
  get "/join/:code", to: "team_invites#new", as: :join_team
  post "/join/:code", to: "team_invites#create"
  put "/join/:code", to: "team_invites#update"
  get "/view_message/:id", to: "messages#view_message", as: :view_message

  get "/dashboard", to: "dashboard#show"
  get "/auth/check", to: "auth#check"

  root to: "dashboard#show"
end

app/controllers/billing/plans_controller.rb
module Billing
  class PlansController < ApplicationController
    skip_before_action :authenticate_user!, only: :success

    def index
      @plans = BillingPlan.all
    end

    def success
      render layout: "auth"
    end
  end
end

app/controllers/billing/subscriptions_controller.rb
module Billing
  class SubscriptionsController < ApplicationController
    skip_before_action :authenticate_user!, only: :success

    def show
      @plans = BillingPlan.visible_paid_plans
    end

    def create
      plan = BillingPlan.new(name: params[:plan])
      current_team.change_plan(plan)
      checkout = create_checkout(with_plan: plan)
      redirect_to checkout.url, allow_other_host: true
    end

    def manage
      portal_url = BillingService.create_portal_link(
        user: current_user,
        team: current_team,
        return_url: billing_settings_url
      )
      redirect_to portal_url, allow_other_host: true
    end

    def success
      render layout: "auth"
    end
  end
end

app/views/billing/subscriptions/_buy_button.html.erb
<%= button_to "Buy #{plan.display_name}", billing_subscriptions_path(plan: plan.id), method: :post, data: { turbo: false }, class: class_name %>

app/views/billing/subscriptions/_mobile_plan.html.erb
<section>
  <div class="px-4 mb-8">
    <h2 class="text-lg leading-6 font-medium text-gray-900"><%= plan.display_name %></h2>
    <p class="mt-4">
      <span class="text-4xl font-extrabold text-gray-900"><%= number_to_currency(plan.current_price, unit: plan.symbol, precision: 0) %></span>
      <span class="text-base font-medium text-gray-500">/mo</span>
    </p>
    <p class="mt-4 text-sm text-gray-500"><%= plan.description %></p>
    <%= render partial: "billing/subscriptions/buy_button", locals: { plan: plan, class_name: "mt-6 block border border-gray-800 rounded-md bg-gray-800 w-full py-2 text-sm font-semibold text-white text-center hover:bg-gray-900 cursor-pointer" } %>
  </div>

  <table class="w-full">
    <caption class="bg-gray-50 border-t border-gray-200 py-3 px-4 text-sm font-medium text-gray-900 text-left">
      Features
    </caption>
    <thead>
      <tr>
        <th class="sr-only" scope="col">Feature</th>
        <th class="sr-only" scope="col">Included</th>
      </tr>
    </thead>
    <tbody class="divide-y divide-gray-200">
      <tr class="border-t border-gray-200">
        <th class="py-5 px-4 text-sm font-normal text-gray-500 text-left" scope="row">AI features</th>
        <td class="py-5 pr-4">
          <!-- Heroicon name: solid/check -->
          <svg class="ml-auto h-5 w-5 text-green-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
          </svg>
          <span class="sr-only">Yes</span>
        </td>
      </tr>

      <tr class="border-t border-gray-200">
        <th class="py-5 px-4 text-sm font-normal text-gray-500 text-left" scope="row">Custom domains</th>
        <td class="py-5 pr-4">
          <!-- Heroicon name: solid/check -->
          <svg class="ml-auto h-5 w-5 text-green-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
          </svg>
          <span class="sr-only">Yes</span>
        </td>
      </tr>

      <tr class="border-t border-gray-200">
        <th class="py-5 px-4 text-sm font-normal text-gray-500 text-left" scope="row">Team members</th>
        <td class="py-5 pr-4">
          <% if plan.available_seats > 1 %>
            <span class="block text-sm text-right text-gray-700">
              Up to <%= plan.available_seats %> users
            </span>
          <% else %>
            <!-- Heroicon name: solid/minus -->
            <svg class="ml-auto h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd" />
            </svg>
            <span class="sr-only">Not included in plan</span>
          <% end %>
        </td>
      </tr>

      <tr class="border-t border-gray-200">
        <th class="py-5 px-4 text-sm font-normal text-gray-500 text-left" scope="row">Message limit</th>
        <td class="py-5 pr-4">
          <span class="block text-sm text-right text-gray-700">
            <%= number_with_delimiter plan.messages_limit %> /mo
          </span>
        </td>
      </tr>
    </tbody>
  </table>

  <table class="w-full">
    <caption class="bg-gray-50 border-t border-gray-200 py-3 px-4 text-sm font-medium text-gray-900 text-left">
      Support
    </caption>
    <thead>
      <tr>
        <th class="sr-only" scope="col">Feature</th>
        <th class="sr-only" scope="col">Included</th>
      </tr>
    </thead>
    <tbody class="divide-y divide-gray-200">
      <tr class="border-t border-gray-200">
        <th class="py-5 px-4 text-sm font-normal text-gray-500 text-left" scope="row">Premium support</th>
        <td class="py-5 pr-4">
          <% if plan.premium_support %>
            <!-- Heroicon name: solid/check -->
            <svg class="ml-auto h-5 w-5 text-green-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
            </svg>
            <span class="sr-only">Yes</span>
          <% else %>
            <!-- Heroicon name: solid/minus -->
            <svg class="ml-auto h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd" />
            </svg>
            <span class="sr-only">No</span>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</section>

app/views/billing/subscriptions/show.html.erb
<h1 class="mt-4 mb-2 text-2xl lg:text-4xl font-semibold text-gray-900 w-full text-center">Select a plan that suits you&hellip;</h1>

<div class="bg-white">
  <div class="max-w-7xl mx-auto bg-white py-16 sm:py-24 sm:px-6 lg:px-8">
    <!-- xs to lg -->
    <div class="max-w-2xl mx-auto space-y-16 lg:hidden">
      <%= render partial: "billing/subscriptions/mobile_plan", collection: @plans, as: :plan %>
    </div>

    <!-- lg+ -->
    <div class="hidden lg:block">
      <table class="w-full h-px table-fixed">
        <caption class="sr-only">
          Pricing plan comparison
        </caption>
        <thead>
          <tr>
            <th class="pb-4 px-6 text-sm font-medium text-gray-900 text-left" scope="col">
              <span class="sr-only">Feature by</span>
              <span>Plans</span>
            </th>

            <% @plans.each do |plan| %>
              <th class="w-1/4 pb-4 px-6 text-lg leading-6 font-medium text-gray-900 text-left" scope="col"><%= plan.display_name %></th>
            <% end %>
          </tr>
        </thead>
        <tbody class="border-t border-gray-200 divide-y divide-gray-200">
          <tr>
            <th class="py-8 px-6 text-sm font-medium text-gray-900 text-left align-top" scope="row">Pricing</th>

            <% @plans.each do |plan| %>
              <td class="h-full py-8 px-6 align-top">
                <div class="relative h-full table">
                  <p>
                    <span class="text-4xl font-extrabold text-gray-900"><%= number_to_currency(plan.current_price, unit: plan.symbol, precision: 0) %></span>
                    <span class="text-base font-medium text-gray-500">/mo</span>
                  </p>
                  <p class="mt-4 mb-16 text-sm text-gray-500"><%= plan.description %></p>
                  <%= render partial: "billing/subscriptions/buy_button", locals: { plan: plan, class_name: "absolute bottom-0 flex-grow block w-full bg-gray-800 border border-gray-800 rounded-md 5 py-2 text-sm font-semibold text-white text-center hover:bg-gray-900 cursor-pointer" } %>
                </div>
              </td>
            <% end %>
          </tr>

          <tr>
            <th class="bg-gray-50 py-3 pl-6 text-sm font-medium text-gray-900 text-left" colspan="4" scope="colgroup">Features</th>
          </tr>

          <tr>
            <th class="py-5 px-6 text-sm font-normal text-gray-500 text-left" scope="row">AI knowledge-base</th>

            <% @plans.each do |plan| %>
              <td class="py-5 px-6">
                <!-- Heroicon name: solid/check -->
                <svg class="h-5 w-5 text-green-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
                </svg>
                <span class="sr-only">Included in Plan</span>
              </td>
            <% end %>
          </tr>

          <tr>
            <th class="py-5 px-6 text-sm font-normal text-gray-500 text-left" scope="row">AI Spam detection</th>

            <% @plans.each do |plan| %>
              <td class="py-5 px-6">
                <!-- Heroicon name: solid/check -->
                <svg class="h-5 w-5 text-green-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
                </svg>
                <span class="sr-only">Included in Plan</span>
              </td>
            <% end %>
          </tr>

          <tr>
            <th class="py-5 px-6 text-sm font-normal text-gray-500 text-left" scope="row">AI Reply Writer</th>

            <% @plans.each do |plan| %>
              <td class="py-5 px-6">
                <!-- Heroicon name: solid/check -->
                <svg class="h-5 w-5 text-green-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
                </svg>
                <span class="sr-only">Included in Plan</span>
              </td>
            <% end %>
          </tr>

          <tr>
            <th class="py-5 px-6 text-sm font-normal text-gray-500 text-left" scope="row">AI Autonomous bot</th>

            <% @plans.each do |plan| %>
              <td class="py-5 px-6">
                <% if plan.ai_autonomous_bot? %>
                  <!-- Heroicon name: solid/check -->
                  <svg class="h-5 w-5 text-green-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
                  </svg>
                  <span class="sr-only">Included in Plan</span>
                <% else %>
                  <!-- Heroicon name: solid/minus -->
                  <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd" />
                  </svg>
                  <span class="sr-only">Not included in plan</span>
                <% end %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th class="py-5 px-6 text-sm font-normal text-gray-500 text-left" scope="row">Custom domains</th>

            <% @plans.each do |plan| %>
              <td class="py-5 px-6">
                <!-- Heroicon name: solid/check -->
                <svg class="h-5 w-5 text-green-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
                </svg>
                <span class="sr-only">Included in Plan</span>
                <span class="text-xs text-gray-500"><%= pluralize(plan.custom_email_addresses, "address") %></span>
              </td>
            <% end %>
          </tr>

          <tr>
            <th class="py-5 px-6 text-sm font-normal text-gray-500 text-left" scope="row">Team members</th>

            <% @plans.each do |plan| %>
              <td class="py-5 px-6">
                <% if plan.available_seats > 1 %>
                  <span class="block text-sm text-gray-700">
                    Up to <%= plan.available_seats %> users
                  </span>
                <% else %>
                  <!-- Heroicon name: solid/minus -->
                  <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd" />
                  </svg>
                  <span class="sr-only">Not included in plan</span>
                <% end %>
              </td>
            <% end %>
          </tr>

          <tr>
            <th class="py-5 px-6 text-sm font-normal text-gray-500 text-left" scope="row">Messages per month</th>

            <% @plans.each do |plan| %>
              <td class="py-5 px-6">
                <span class="block text-sm text-gray-700">
                  <%= number_with_delimiter plan.messages_limit %> /mo
                </span>
              </td>
            <% end %>
          </tr>

          <tr>
            <th class="bg-gray-50 py-3 pl-6 text-sm font-medium text-gray-900 text-left" colspan="4" scope="colgroup">Support</th>
          </tr>

          <tr>
            <th class="py-5 px-6 text-sm font-normal text-gray-500 text-left" scope="row">Premium support</th>

            <% @plans.each do |plan| %>
              <td class="py-5 px-6">
                <% if plan.premium_support %>
                  <!-- Heroicon name: solid/check -->
                  <svg class="h-5 w-5 text-green-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
                  </svg>
                  <span class="sr-only">Included in plan</span>
                <% else %>
                  <!-- Heroicon name: solid/minus -->
                  <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd" />
                  </svg>
                  <span class="sr-only">Not included in plan</span>
                <% end %>
              </td>
            <% end %>
          </tr>
        </tbody>
        <tfoot>
          <tr class="border-t border-gray-200">
            <th class="sr-only" scope="row">Choose your plan</th>

            <% @plans.each do |plan| %>
              <td class="pt-5 px-6">
                <%= render partial: "billing/subscriptions/buy_button", locals: { plan: plan, class_name: "block w-full bg-gray-800 border border-gray-800 rounded-md py-2 text-sm font-semibold text-white text-center hover:bg-gray-900 cursor-pointer" } %>
              </td>
            <% end %>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>

app/views/billing/subscriptions/success.html.erb
<div class="text-center">
  <h2 class="mb-5 text-xl lg:text-2xl font-bold text-gray-900">
    Thanks for subscribing 🎉
  </h2>

  <p class="mb-6">Your subscription has been set up and will be billed automatically each month.</p>

  <%= link_to "Back to Happi", message_threads_path, class: "button -primary -rounded -lg" %>
</div>